### ISSUE TITLE
编辑器异常

### ISSUE THREAD

**Issue by iNeverSleeeeep** [Tencent/behaviac#10]
behaviac/tools/designer/External/DockPanel/WinFormsUI/Docking/VS2005DockPaneStrip.cs :916
![image](https://cloud.githubusercontent.com/assets/8469299/25330582/b823173e-2912-11e7-82f2-217efe8befb7.png)

再现方法是在编辑树时为当前agent添加method

**Comment by cainhuang** [comment]
你试下最新版的3.6.31看看还能不能出现这个问题
