### ISSUE TITLE
BUG：c# 版本 使用计算节点时如果左值是值类型, 生成的代码报错

### ISSUE THREAD

**Issue by voidweapon** [Tencent/behaviac#106]
版本：3.6.39
语言：c#
复现步骤：
1. 添加新agent
2. 在这个agent里添加一个float类型的成员变量a
3. 在行为树中构建一个计算节点，表达式a = 1 + 1
4.导出行为树到c#
结果：
 产生错误：error CS0445: Cannot modify the result of an unboxing conversion
自动生成的代码
`		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)`
`{`
`			EBTStatus result = EBTStatus.BT_SUCCESS;`
			`int opr1 = 1;`
			`int opr2 = 1;`
			`(int)AgentMetaVisitor.GetProperty(pAgent, "a") = (int)(opr1 + opr2);`
			`return result;`
`}`
==========================================================

**Comment by OwenNCai** [comment]
> 版本：3.6.39
> 语言：c#
> 复现步骤：
> 
> 1. 添加新agent
> 2. 在这个agent里添加一个float类型的成员变量a
> 3. 在行为树中构建一个计算节点，表达式a = 1 + 1
>    4.导出行为树到c#
>    结果：
>    产生错误：error CS0445: Cannot modify the result of an unboxing conversion
>    自动生成的代码
>    `		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)`
>    `{`
>    `			EBTStatus result = EBTStatus.BT_SUCCESS;`
>    `int opr1 = 1;`
>    `int opr2 = 1;`
>    `(int)AgentMetaVisitor.GetProperty(pAgent, "a") = (int)(opr1 + opr2);`
>    `return result;`
>    `}`
>    ==========================================================

怎么解决的？

**Comment by hongkunan** [comment]
同样碰到这个问题了，怎么解决的呢？为什么这个单被关闭了呢？

**Comment by kennizy** [comment]
把(int)AgentMetaVisitor.GetProperty(pAgent, "a") = (int)(opr1 + opr2);

**Comment by kennizy** [comment]
把(int)AgentMetaVisitor.GetProperty(pAgent, "a") = (int)(opr1 + opr2);改成(AgentMetaVisitor.Property(pAgent, "a", (int)(opr1 + opr2)) ;

**Comment by kennizy** [comment]
把(int)AgentMetaVisitor.GetProperty(pAgent, "a") = (int)(opr1 + opr2);改成(AgentMetaVisitor.SetProperty(pAgent, "a", (int)(opr1 + opr2))
