### ISSUE TITLE
官方网站无法访问

### ISSUE THREAD

**Issue by Kenny-G** [Tencent/behaviac#128]
官方网站是停止维护了吗... 最新文档请问哪里还可以获取.

**Comment by dreamfairy** [comment]
官网爆炸了 + 1， 是不是不维护了

**Comment by jintemp** [comment]
https://www.behaviac.com 打不开 +1

**Comment by pjkui** [comment]
前段时间升级，造成官网配置被修改，所以重新进行了资源申请和重新部署

**Comment by HellGame** [comment]
现在官网还是无法访问啊

**Comment by gsw945** [comment]
从下面这个链接进入可以打开：
- https://www.behaviac.com/language/zh/首页/
