### ISSUE TITLE
BehaviacDesigner还有在维护吗？我私底下优化了BehaviacDesigner的性能，打算看情况提PullRequest

### ISSUE THREAD

**Issue by ankisme** [Tencent/behaviac#134]
我想问问BehaviacDesigner是否还在维护

我私底下优化了BehaviacDesigner的性能，但是因为是私底下改的代码，不清楚符不符合官方的标准，也还没全面检查过逻辑，所以，如果还有在维护的话，我想整理和检查一下我改动的代码，然后提PullRequest，而且，我改的这些代码要求.Net Framework更新到4.7.1版本（因为要支持c#的Parallel），如果不符合官方要求的话我就不提交了。另外，代码也需要官方检查一下。

之所以优化BehaviacDesigner性能，是因为我所在的项目中有几百个行为树文件，而且看样子还会再新增很多行为树文件，用BehaviacDesigner导出时卡很久，所以就clone了源码进行修改了。

**Comment by kopfly** [comment]
您好，请问可以说说行为树导出效率优化的内容吗？我也碰到这个问题了，准备clone源码研究下。如果可以提供相关patch就太感谢了

**Comment by ankisme** [comment]
> 您好，请问可以说说行为树导出效率优化的内容吗？我也碰到这个问题了，准备clone源码研究下。如果可以提供相关patch就太感谢了

https://gitee.com/ankisme/behaviac-public

好，我刚刚整理了下然后放在gitee了，我后续又改了挺多BehaviacDesigner代码，而且删掉了一些我用不到的功能，所以已经跟现有的behaviac不兼容了，只能自己私底下用，我不知道你用不用得上这个，具体你自己试用看看吧

**Comment by kopfly** [comment]
收到 感谢
