### ISSUE TITLE
debug 内存泄漏 连调

### ISSUE THREAD

**Issue by haoA2580** [Tencent/behaviac#143]
debug模式下连调会产生内存泄漏 程序卡住
release模式下不会产生内存泄漏 程序运行流畅 但是无法连调 
请问有什么方法可以解决连调与内存泄漏的问题吗

**Comment by pjkui** [comment]
如果查內存泄露，需要关闭debug模式。debug模式是用来联调的，不能用于线上环境。

**Comment by haoA2580** [comment]
> 



> 

因为在debug模式下才可以联调 但是debug模式下会有内存泄漏 导致程序运行卡死无法调试 现在的话 是想在debug模式下避免内存泄漏的同时实现联调 请问有什么方法可以解决吗？

**Comment by pjkui** [comment]
内存泄露不会影响联调卡死，建议查一下卡死的原因。

**Comment by haoA2580** [comment]
> 

好的好的 谢谢 辛苦啦
