### ISSUE TITLE
Struct定义的引用类型去除后编译错误

### ISSUE THREAD

**Issue by jinq0123** [Tencent/behaviac#16]
定义`Struct A`, 默认为引用类型。`MyAgent` 添加属性 `a`, 类型为 `A`. 然后将 `Struct A` 定义中的引用类型去除，重新导出。代码 `behaviac_agent_member_visitor.h` 没有相应更改，造成编译错误。
```C++
struct PROPERTY_TYPE_MyAgent_a { };
template<> inline A*& MyAgent::_Get_Property_<PROPERTY_TYPE_MyAgent_a>()
{
	return this->a;
}
```
而 `a` 已不是指针:
```C++
class MyAgent : public behaviac::Agent
{
	private: A a;
...
```

从非引用类型改成引用类型则是正常的。

**Comment by cainhuang** [comment]
谢谢反馈，等下个版本3.6.39会修复该bug
