### ISSUE TITLE
测试中发现了内存泄漏，这里为什么要把析构函数给注释掉呢？

### ISSUE THREAD

**Issue by rogerhdh** [Tencent/behaviac#18]
https://github.com/Tencent/behaviac/blob/cdae7791f530dae1919ae65a73b43f733376a5df/integration/demo_running/behaviac/BehaviorTree/Nodes/Composites/Referencebehavior.cs#L205

析构函数被注释掉以后，m_subTree成员变量没有被销毁，服务器中出现了内存不断上涨的问题

**Comment by jonygli** [comment]
C#中，析构函数的存在反而推迟了资源的释放。如果有内存泄漏，应该实现Dispose函数吧。
