### ISSUE TITLE
状态机与行为树嵌套问题

### ISSUE THREAD

**Issue by rooong** [Tencent/behaviac#37]
在子树文档中的描述，状态机与行为树可以相互嵌套。在btunittest中的例子中是可以嵌套，但是我重新创建一个状态机，想为状态机添加一棵行为子树，问题：
1.从左边子树节点拉到状态机中作为节点，鼠标一直是禁止符号，不能创建
2.从已有的行为树拉到状态机中作为节点，鼠标一直是禁止符号，不能创建

有人知道什么情况吗

**Comment by kecookier** [comment]
状态节点需要添加转换附件，鼠标从转换附件上拖拽可以链接状态节点和子树。
如果不添加转换附件，是不能拖拽连接的，鼠标会显示禁止符号。

**Comment by rooong** [comment]
@kecookier 状态节点已经添加转换附件了，就是不能拖拽子树节点到行为树编辑框中，一直是禁止符号

**Comment by kecookier** [comment]
我这儿可以直接拖过来，没出现你说的情况，编辑器的版本是3.6.39吗？

**Comment by kecookier** [comment]
![23b51f06-933a-4516-b466-78c11f859e67](https://user-images.githubusercontent.com/3390068/39852734-b61ad26e-5450-11e8-97b4-dbaacd4b109e.jpg)

**Comment by rooong** [comment]
@kecookier 是3.6.39版本，不知道哪里的问题，我重新安装一遍，就可以了。
