### ISSUE TITLE
事件fire传入的参数不能用做动作节点函数的参数

### ISSUE THREAD

**Issue by snuc** [Tencent/behaviac#44]
在编辑器下无法选择，如图所示
![issue1](https://user-images.githubusercontent.com/781563/41144489-a9caaf3e-6b2f-11e8-8deb-87d9dc5b483d.png)
![image](https://user-images.githubusercontent.com/781563/41144555-de6d893c-6b2f-11e8-8966-1ab488025ee8.png)
Self下拉按钮没有param0

最后手动修改xml解决了……

**Comment by javelinlin** [comment]
我也发现这类问题。
起初以为我是配置问题或是类型不匹配。
然而发现好多方法、属性设置的地方都有这个问题。
看来我也只能手动修改xml的方式了。
:(
