### ISSUE TITLE
如何使用behaviac的事件？

### ISSUE THREAD

**Issue by kaclok** [Tencent/behaviac#56]
![snipaste_2018-08-27_17-53-40](https://user-images.githubusercontent.com/11922982/44653739-21f34080-aa22-11e8-9a5e-2a09b0ba5e51.png)

我在行为树执行的时候（次数阻塞于wait signal节点），通过外部代码fireevent，但是总是在行为树中不能正确接收事件，以至于不能正确回调， 想问一下， 会是神马问题。

**Comment by kaclok** [comment]
没有把事件监听到第一个节点上导致了这个问题。

**Comment by BUGyyc** [comment]
@kaclok 请教一个问题

**Comment by BUGyyc** [comment]
@kaclok https://github.com/Tencent/behaviac/issues/113
