### ISSUE TITLE
关于behaviac在实际使用中的一些问题

### ISSUE THREAD

**Issue by iNeverSleeeeep** [Tencent/behaviac#9]
在研究是否可以把behaviac应用到我们项目中来。有两个问题想请教一下：
1、behaviac是否在实际项目中使用过？是否有上线项目使用？
    我看到behaviac的官网下面有用户案例，是这些项目都使用了behaviac作为ai编辑器吗？例如王者荣耀这款游戏，是在什么场景下使用了behaviac？
2、编辑器的使用者的定位是程序还是策划？

另外顺便提两个疑似BUG
1、在action中添加参数信息。将该action拖入行为树中，再在类型心中中将参数信息删除，应用。行为树中的参数信息不会删除。删除行为树中的节点，重新拖入action指定方法，还是需要参数信息。
2、action中不能指定决定状态的函数。我不知道有没有设置对，方法返回类型void，决定状态的选项是invalid，想指定的函数的参数是0个，返回值是status。

还有一个可能存在问题的地方
1、Prefab解除预制实例（我理解这个功能是与prefab解绑定），背景还是显示灰色的Prefab[...]，不能直观判断解绑定了。

**Comment by cainhuang** [comment]
1. 官网下面滚动的那些游戏都使用了behaviac组件，基本都是用于角色AI。
2. 编辑器基本是交给策划使用，并且用于编辑行为树。程序需要在编辑器中创建Agent类及其属性和方法，当然策划也可以创建。

**Comment by iNeverSleeeeep** [comment]
谢谢回答。
刚才说的哪个疑似BUG。我再现不出来了。。
