### ISSUE TITLE
可继承的Agent

### ISSUE THREAD

**Issue by swicksu** [Tencent/behaviac#90]
我刚接触Behaviac, 在看HelloWorld, 用的Unity
我发现当我`导出全部`时, 会覆盖我原有的`FirstAgent`
我尝试写一个新的Class去继承`FirstAgent`, 并挂上运行
除了自定义的`SayHello`方法不是Virtual, 我无法继承
改成Virtual后覆盖, HelloWorld正常运行, 并且导出不会影响到.

我觉得生成的自定义方法和字段可以定义成Virtual, 然后自己去重写.
个人觉得可以改进使用体验.

**Comment by pjkui** [comment]
目前的工作流，一般是第一步：先在编辑器里添加agent并给agent添加方法、第二步：导出生成agent和相关行为树，最后一步在在生成的agent类的方法里面做具体实现。这是正常的工作流程。
如果先自己写了Agent类，就会遇到上面的问题。这个时候做好代码合并就行了。
